### ISSUE TITLE
Problem with !model

### ISSUE THREAD

**Issue by Alkenos** [BlackFalcons/serverguard-plus#1]
Hello

When i try to setmodel me with this command : !model Alkenos models/lb/solve_scp_fim/solve_fim.mdl my model set to kleiner is it normal ?

Regards

Alkenos

**Comment by NobleFalcon** [comment]
The `!model` command is a beta feature as you know and the current fallback when an invalid model name or path is given is the kleiner model, this is not something I have implemented it is the default model for when an invalid one is given to the method provided by Garry's Mod. I am not entirely sure why it does not set you to your requested model. But my suspicion is that you just gave it an invalid model. Did you copy the path from your props menu or did you copy it from the player model selector in the `C` menu? I have at least noticed that the model paths copied from the context menu is laying in a `/player` folder and those from the props menu does not and they don't work either.

So my suggestion to you is to copy the path from your context menu, the command will spit out the short name after you have executed the command once with the full path so that should make it easier for you in the future.

Hope this helps @Alkenos

**Comment by Alkenos** [comment]
Thanks for the explanation. I will try it now and keep you informed.

**Comment by Alkenos** [comment]
it works thanks for the help
